# -*- coding: utf-8 -*-
"""AI-Course-Recommendation-System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oRYn4whQFEK3lUTiR7vQNEOezMjwtGX
"""

import os
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# !pip install gradio  (Run this if Gradio is not installed)
import gradio as gr
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Define the path of files inside the downloaded folder
print("Files in dataset path:", os.listdir(path))

# Find the CSV file automatically in the folder
csv_file = [f for f in os.listdir(path) if f.endswith('.csv')][0]
df = pd.read_csv(os.path.join(path, csv_file))

# Display the first rows of the dataset to check the actual column names
print(df.head())
print("Columns:", df.columns)

# 1. Combine available features (Title and Subject) to create text data for TF-IDF
df['combined_features'] = df['course_title'].fillna('') + ' ' + df['subject'].fillna('')

# 2. Apply TF-IDF Vectorizer
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined_features'])

# 3. Compute Cosine Similarity between courses
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# 4. Function to recommend top N courses based on a given course title
def recommend_courses(course_title, num_recommendations=4):
    if course_title not in df['course_title'].values:
        return f"The course '{course_title}' is not found in the dataset."

    # Get the index of the course
    idx = df[df['course_title'] == course_title].index[0]

    # Compute similarity scores
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Exclude the course itself and take the top N recommendations
    sim_scores = sim_scores[1:num_recommendations+1]

    course_indices = [i[0] for i in sim_scores]
    similarity_scores = [i[1] for i in sim_scores]

    # Build and return the recommendations as a sorted DataFrame
    recommendations = df.iloc[course_indices][['course_title', 'subject', 'level', 'price']].copy()
    recommendations['similarity_score'] = [round(score, 3) for score in similarity_scores]

    return recommendations

# --- System Test (Course-based Recommendation) ---
sample_course = df['course_title'].iloc[0]
print(f"--- Recommendations for: '{sample_course}' ---")
print(recommend_courses(sample_course, num_recommendations=4))


# --- 5. User Input Recommendation System ---
def user_recommendation_system():
    print("\n--- Smart Course Recommendation System ---")
    user_input = input("Enter a topic or skills you want to learn (e.g., Business Finance, Python, Excel): ")

    temp_df = df.copy()
    all_texts = temp_df['combined_features'].tolist()
    all_texts.insert(0, user_input) # Insert user input at the beginning

    user_tfidf = TfidfVectorizer(stop_words='english')
    user_tfidf_matrix = user_tfidf.fit_transform(all_texts)

    # Calculate cosine similarity between user input (index 0) and all courses
    cosine_sim_user = cosine_similarity(user_tfidf_matrix[0:1], user_tfidf_matrix[1:])

    sim_scores = list(enumerate(cosine_sim_user[0]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    top_indices = [i[0] for i in sim_scores[:4]]
    top_scores = [i[1] for i in sim_scores[:4]]

    print(f"\nTop Recommended Courses for your interest: '{user_input}'\n" + "="*50)
    results = temp_df.iloc[top_indices][['course_title', 'subject', 'level', 'price']].copy()
    results['similarity_score'] = [round(score, 3) for score in top_scores]

    return results

# Uncomment the line below to test interactive user input:
# display(user_recommendation_system())

# --- 6. Knowledge Graph (User -> Skills -> Topics -> Courses) ---
G = nx.DiGraph()

user_node = "User: Student"
skill_1 = "Skill: Data Analysis"
skill_2 = "Skill: Finance"
topic_node = "Topic: Business Finance"

course_1 = df['course_title'].iloc[0]
course_2 = df['course_title'].iloc[2]

# Add nodes and edges
G.add_edge(user_node, skill_1, relationship='has_skill')
G.add_edge(user_node, skill_2, relationship='has_skill')
G.add_edge(skill_1, topic_node, relationship='belongs_to')
G.add_edge(skill_2, topic_node, relationship='belongs_to')
G.add_edge(topic_node, course_1, relationship='recommends')
G.add_edge(topic_node, course_2, relationship='recommends')

# Draw Knowledge Graph
plt.figure(figsize=(12, 8))
pos = nx.spring_layout(G, k=0.9, seed=42)

node_colors = []
for node in G.nodes():
    if "User" in node:
        node_colors.append('#ff9999')
    elif "Skill" in node:
        node_colors.append('#66b3ff')
    elif "Topic" in node:
        node_colors.append('#99ff99')
    else:
        node_colors.append('#ffcc99')

nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=3500, alpha=0.9)
nx.draw_networkx_edges(G, pos, width=2, arrowsize=20, edge_color='gray', connectionstyle='arc3,rad=0.1')
nx.draw_networkx_labels(G, pos, font_size=9, font_family='sans-serif', font_weight='bold')

edge_labels = nx.get_edge_attributes(G, 'relationship')
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8)

plt.title("AI Course Recommendation Knowledge Graph\n(User -> Skills -> Topics -> Courses)", fontsize=14, fontweight='bold')
plt.axis('off')
plt.tight_layout()
plt.show()

def recommend_via_ui(user_interest):
    # Same recommendation logic
    all_texts = df['combined_features'].tolist()
    all_texts.insert(0, user_interest)

    tfidf = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf.fit_transform(all_texts)

    cosine_sim_user = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:])
    sim_scores = sorted(list(enumerate(cosine_sim_user[0])), key=lambda x: x[1], reverse=True)[:4]

    top_indices = [i[0] for i in sim_scores]

    # Prepare recommendations dataframe
    recommended_df = df.iloc[top_indices][['course_title', 'subject', 'level', 'price']].copy()
    return recommended_df

# Create a clean web interface
iface = gr.Interface(
    fn=recommend_via_ui,
    inputs=gr.Textbox(lines=2, placeholder="Type your interest or skill here (e.g., Excel, Finance, Python)..."),
    outputs="dataframe",
    title="AI Course Recommendation System",
    description="Enter the skill or topic you want to learn, and we will recommend the best matching courses for you!"
)

# Launch the interface
iface.launch()